### ISSUE TITLE
The cursor moves to the top after each modification of the value

### ISSUE THREAD

**Issue by hkkxx** [FIameCaster/prism-react-editor#2]
The cursor moves to the top after each modification of the value。
I don't know why？I don't want the cursor to move.

react：

`
// eslint-disable-next-line react/prop-types
function MyExtensions({editor}) {
    useBracketMatcher(editor)
    useHightlightBracketPairs(editor)
    useTagMatcher(editor)
    useHighlightMatchingTags(editor)
    useSearchWidget(editor)
    useHighlightSelectionMatches(editor)
    useCopyButton(editor)
    useCursorPosition(editor)
    useDefaultCommands(editor)
    useEditHistory(editor, 10)
    return <IndentGuides editor={editor}/>
}
......
      <Editor language="json"
              value={geoStr}
              wordWrap={true}
              insertSpaces={true}
              style={{"width": "100%"}}
              readOnly={false}
              onUpdate={(value) => dispatch(setgeoValue(value))}>
          {editor => <MyExtensions editor={editor}/>}
      </Editor>
`
![屏幕截图 2024-12-22 192610](https://github.com/user-attachments/assets/4fa96424-53fb-41bf-ae1e-c8d7c0ffaf9e)

：）

**Comment by jonpyt** [comment]
This is caused by changing the `value` prop inside the `onUpdate` handler. This is a pitfall mentioned in the [readme](https://github.com/FIameCaster/prism-react-editor?tab=readme-ov-file#pitfall). The `value` prop should be treated as a default value and should not be changed inside the `onUpdate` handler.

**Comment by pensono** [comment]
What's the correct way to update the component's text?

In my case, I'm streaming in text generated by an AI

**Comment by jonpyt** [comment]
> What's the correct way to update the component's text?
> 
> In my case, I'm streaming in text generated by an AI

You should change the `value` prop to change the component's text. When changing the `value` prop, the cursor position and edit history will be reset. In your case, changing the `value` prop makes sense.
